name: CD Workflow
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Workflow"]
    branches: [main]
    types: 
      - completed

jobs:
    development:
        environment: dev
        runs-on: self-hosted
        steps:
            #Checking out the repo 
            - run: | 
                docker image load --input /tmp/myimage.tar
                docker run -dp 3000:3000 duartedias471/ci_test:v1 --name=app
                docker ps 
                curl `docker inspect --format='{{.NetworkSettings.IPAddress}}' epic_diffie`:3000/api/latest-releases
                docker stop app

            
          