name: CD Workflow
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Workflow"]
    branches: [main]
    types: 
      - completed

jobs:
    production:
        environment: dev
        runs-on: self-hosted
        steps:
          #:3000
            #Checking out the repo 
            - run: | 
                docker image load --input /tmp/myimage.tar
                docker run --name=app -dp 3000:3000 duartedias471/ci_test:v1
                docker ps 
                sleep 10
                curl `docker inspect --format='{{.NetworkSettings.IPAddress}}' app`:3000/api/latest-releases
                docker stop app
                docker rm app

            - name: checkout
              uses: actions/checkout@v4 

            -
             name: Build and push
             uses: docker/build-push-action@v5
             with:
              push: true
              tags: ${{secrets.DOCKERHUB_USERNAME}}/${{vars.APP_NAME}}:v1
          

            
          