name: CD Workflow
on:
  workflow_run:
    workflows: ["CI Workflow"]
    branches: [main]
    types: 
      - completed

jobs:
    development:
        environment: dev
        runs-on: self-hosted
        steps:
            #Checking out the repo 
            - run: echo test