name: CD Workflow
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI Workflow"]
    branches: [main]
    types: 
      - completed

jobs:
    production:
        environment: prod
        runs-on: self-hosted
        steps:
            #Checking out the repo 
            - run: | 
                docker image load --input /tmp/myimage.tar
                docker run --name=app -dp 3000:3000 duartedias471/ci_test:v1
                docker ps 
                sleep 10
                curl 172.17.0.3:3000/api/latest-releases
                docker stop app
          

            
          